import Head from "next/head";
import Nav from "../ui/Nav";
import Sidebar from "../ui/Sidebar";

const Layout = ({ children }) => {
	return (
		<>
			<Head>
				<title>Esprits Frappeurs</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Sidebar />
				<div className="pageContainer">
					<Nav />
					<div className="pageContent">{children}</div>
				</div>
			</main>
		</>
	);
};

export default Layout;
