import Head from "next/head";
import Nav from "../ui/Nav";

const Layout = ({ children }) => {
	return (
		<>
			<Head>
				<title>Exprits Frappeurs</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Nav />
				<div>
					<div>{children}</div>
				</div>
			</main>
		</>
	);
};

export default Layout;
